config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'pages/recommendations'
  get 'pages/blogs'
  get 'pages/news'
  get 'pages/about'

  resources :testimonials
  resources :recipes do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
    has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action

  def home
    @user = current_user
    @testimonials = Testimonial.all
  end

  def recommendations
    @user = current_user
  end

  def blogs
    @user = current_user
  end

  def news
    @user = current_user
  end

  def about
    @user = current_user
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
    @user = current_user
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  def index
    @testimonials = Testimonial.all
    @user = current_user
  end

  def show
    @testimonial = Testimonial.find(params[:id])
    @user = current_user
  end

  def new
    @testimonial = Testimonial.new
    @user = current_user
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)
    if @testimonial.save
      redirect_to testimonials_path
    else
      render :new
    end
  end


  def edit
    @testimonial = Testimonial.find(params[:id])
    @user = current_user
  end

  def update
    @testimonial = Testimonial.find(params[:id])
    @testimonial.update(testimonial_params)
    redirect_to testimonials_path
  end

  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy
    redirect_to testimonials_path
  end

  private
    def testimonial_params
      params.require(:testimonial).permit(:name, :profession, :content, :date, :photo)
    end

    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodamentalWeb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= params[:controller].tr("/", "-") %> <%= params[:action] %>">
    <%= render "shared/navbar" unless @disable_nav %>
    <%= render "shared/flashes" %>
    <%= yield %>
     <%= render 'shared/footer' unless @disable_footer %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hola About</h1>

app/views/pages/blogs.html.erb
<h1>Hola Blogs</h1>

app/views/pages/home.html.erb
<div class="banner-wrapper">
  <div style="background-image: url('https://images.unsplash.com/photo-1474440692490-2e83ae13ba29?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80'); background-repeat: no-repeat; background-position:   center center; background-size: cover; width: 100%; height: 900px;" id="banner">
    <div class="foodamental-text-wrapper">
      <h1>FOODAMENAL</h1>
      <a href="https://www.foodamental.com/" class="visit-btn">DISCOVER</a>
    </div>
  </div>
</div>

<div class="">

  <!-- ENUNCIADO -->
  <div class="enun-wrapper">
     <h2>
       Roughly one-third of the food produced in the world for human consumption every year - approximately 1.3 billion tonnes - gets lost or wasted.Let's create awareness to distribute and consume our food in a better way.
     </h2>
  </div>
  <!-- FINISH ENUNCIADO -->

  <!-- RECOMENDATIONS -->
  <div class="recomendation-wrapper">
    <div>
      <h1 style="font-family: Abhaya;">
        RECOMENDATIONS
      </h1>
      <h5>Adopt a healthier, more sustainable diet</h5>
      <div class="learn-btn-wrapper">
        <%= link_to "Learn more", "pages/recommendations", class: "learn-more-btn" %>
      </div>
    </div>
    <div>
      <%= link_to image_tag("https://images.unsplash.com/photo-1464454709131-ffd692591ee5?ixlib=rb-1.2.1&   ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2676&q=80", alt: "food", class: "rec-img") %>
    </div>
  </div>
  <!-- FINISH RECOMENDATIONS -->

    <!-- FOOD WASTE LATEST NEWS -->
   <div class="latest-new-wrapper">

     <div class="left-cont-latestnews">
        <div class="text-ln-wrapper">
          <h1 style="font-family: Abhaya;">
            Latest News
          </h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem,
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </p>
        </div>
        <div class="latestnews-text-wrapper">
          <%= link_to image_tag("https://www.usda.gov/sites/default/files/2021-10/flw-roundtable-food-waste-reduction-blog-102821.jpg", class:   "wfood-img") %>
        </div>
     </div>

     <div class="right-cont-latestnews">
       <div class="right-cont-wrapper">
         <h4>View All News</h4>
         <h1 style="font-family: Abhaya;">
            LOREM IPSUM THEM
            LOREM IPSUM THEM
            LOREM.
          </h1>
          <h3>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem,
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </h3>
          <div class="latestnews-btn-wrapper">
            <%= link_to "READ MORE", "pages/news",  class: "latestnews-btn" %>
          </div>
       </div>
     </div>
   </div>
   <!-- FINISH FOOD WASTE LATEST NEWS -->

    <!-- TESTIMONIALS -->
    <div class="testimonials-wrapper">
       <div class="left-cont-testimonials">
       </div>
       <div class="right-cont-testimonials">
         <div class="testimonials-title">
            <p>Testimonials</p>
            <p>Come to us, saving food</p>
         </div>
            <p class="testimonial-paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem,
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
       </div>
    <!-- TESTIMONIALS SLIDE -->
   <div class="card-group">
         <% @testimonials.each do |testimonial| %>
          <% if testimonial.photo.attached? %>
          <div class="card-style">
            <%= link_to edit_testimonial_path(testimonial) do %>
              <%= cl_image_tag testimonial.photo.key, height: 400, width: 400, crop: :fill, class:"testimonial-img" %>
            <%end%>
          </div>
           <%end %>
        <% end %>
    </div>
    <!-- FINISH TESTIMONIALS SLIDE -->
    </div>
    <!-- FINISH TESTIMONIALS -->

    <!-- TESTIMONIALS TEXT -->
    <div class="testimonial-text-wrapper">
      <div class="each-testimonial">
         <% @testimonials.each.first(1).each do |testimonial| %>
            <h2><span><%= testimonial.name.upcase %></span> - <%= testimonial.profession.upcase %></h2>
            <h4><%= testimonial.content %></h4>
          <% end %>
      </div>
    </div>
    <!-- FINISH TESTIMONIALS TEXT -->
    <!-- FOOTER -->
</div>

app/views/pages/news.html.erb
<div class="container news-wrapper">
   <h1 style="font-family: Abhaya; text-align: center;">LATEST NEWS</h1>
   <div class="news-details">
    <div style="background-image: url('https://images.unsplash.com/photo-1621562010213-c95682af384b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80')" class="news-item"></div>
    <div class="news-item__content">
      <h2>News Title</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquet, nisl nisl aliquet nunc, sed aliquet nisl lorem quis nunc. Sed euismod, nunc ut aliquam aliquet, nisl nisl aliquet nunc, sed aliquet nisl lorem quis nunc.</p>
      <a href="#">Read More</a>
    </div>
   </div>
   <div class="news-details">
    <div style="background-image: url('https://www.supermarketnews.com/sites/supermarketnews.com/files/styles/article_featured_retina/public/uploads/2016/06/wastegetty1156.jpg?itok=wteWyH-s')" class="news-item"></div>
    <div class="news-item__content">
      <h2>News Title</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquet, nisl nisl aliquet nunc, sed aliquet nisl lorem quis nunc. Sed euismod, nunc ut aliquam aliquet, nisl nisl aliquet nunc, sed aliquet nisl lorem quis nunc.</p>
      <a href="#">Read More</a>
    </div>
   </div>
   <div class="news-details">
    <div style="background-image: url('https://marvel-b1-cdn.bc0a.com/f00000000209359/www.uoguelph.ca/alliance/sites/default/files/styles/large/public/Greenhouse.jpg?itok=pXoI7SpT')" class="news-item"></div>
    <div class="news-item__content">
      <h2>News Title</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam aliquet, nisl nisl aliquet nunc, sed aliquet nisl lorem quis nunc. Sed euismod, nunc ut aliquam aliquet, nisl nisl aliquet nunc, sed aliquet nisl lorem quis nunc.</p>
      <a href="#">Read More</a>
    </div>
   </div>
</div>

app/views/pages/recommendations.html.erb
<div class="container recom-wrapper">
  <div class="recom-header">
    <div class="left-tr">
      <h1 style="font-family: Abhaya;">Tips and Recommendations</h1>
       <p>
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nunc nisl sit amet nisl. Sed euismod.
       </p>
       <div class=" card mb-3" style="max-width: 25rem;  background-color: #6A961F; color: #fff; border-radius: 5px;">
        <div class="card-header">Tip 1</div>
        <div class="card-body">
          <h5 class="card-title">Adopt a healthier, more sustainable diet</h5>
        </div>
       </div>
       <div class="card mb-3" style="max-width: 25rem; background-color: #6A961F; color: #fff;">
        <div class="card-header">Tip 2</div>
        <div class="card-body">
          <h5 class="card-title">Buy only what you need</h5>
        </div>
       </div>
       <div class="card mb-3" style="max-width: 25rem; background-color: #6A961F; color: #fff;">
        <div class="card-header">Tip 3</div>
        <div class="card-body">
          <h5 class="card-title">Pick ugly fruit and vegetables</h5>
        </div>
       </div>
       <div class="card mb-3" style="max-width: 25rem; background-color: #6A961F; color: #fff;">
        <div class="card-header">Tip 4</div>
        <div class="card-body">
          <h5 class="card-title">Store food wisely</h5>
        </div>
       </div>
       <div class="card mb-3" style="max-width: 25rem; background-color: #6A961F; color: #fff;">
        <div class="card-header">Tip 5</div>
        <div class="card-body">
          <h5 class="card-title">Understand food labelling</h5>
        </div>
       </div>

        <!--<p>
         <img type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample" src=<%#= image_path("idea-2.png") %> width="32" height="32" class="d-inline-block align-top" alt="">
        </p>

         <div style="min-height: 120px;">
           <div class="collapse collapse-horizontal" id="collapseWidthExample">
              <div class="card-tip">
                <div class="text-tip-wrapper">
                  <p>Adopt a healthier, more sustainable diet</p>
                </div>
              </div>
          </div>
        </div>-->
    </div>
    <div class="right-tr">
        <img src="https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80" alt="Tips and Recommendations" class="recom-img">
    </div>
  </div>
    <div class="img-gallery-wrapper">
     <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
          <div class="card-ui">
            <div style="background-image: url(https://images.unsplash.com/photo-1532460854099-4de86fea4a11?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2674&q=80); height: 100%; background-size:cover;" class="card-img" alt="...">
              <div class="card-text">
                 <h3>more sustainable diet</h3>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card-ui">
            <div style="background-image: url( https://images.unsplash.com/photo-1593026122758-19bebc625104?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80); height: 100%; background-size:cover;" class="card-img" alt="...">
              <div class="card-text">
                 <h3>Buy only what you need</h3>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card-ui">
            <img src="https://images.unsplash.com/photo-1414450397866-85f90db48714?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1920&q=80" class="card-img" alt="...">
            <div class="card-text">
                 <h3>Be creative by preserving food.</h3>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card-ui">
            <img src="https://images.unsplash.com/photo-1606859191214-25806e8e2423?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2635&q=80" class="card-img" alt="...">
            <div class="card-text">
                 <h3>Store food wisely</h3>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card-ui">
            <img src="https://images.unsplash.com/photo-1414450397866-85f90db48714?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1920&q=80" class="card-img" alt="...">
            <div class="card-text">
                 <h3>Understand food labelling</h3>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card-ui">
            <img src="https://images.unsplash.com/photo-1498491480129-04f6d95c90be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80" class="card-img" alt="...">
            <div class="card-text">
                 <h3>Pick ugly fruit and vegetables</h3>
            </div>
          </div>
        </div>
     </div>
     </div>
</div>

<!--<h3>Adopt a healthier, more sustainable diet</h3>
<h3>Buy only what you need</h3>
<h3>Pick ugly fruit and vegetables</h3>
<h3>Store food wisely</h3>
<h3>Understand food labelling</h3>
<h3>Start small</h3>-->

app/views/recipes/index.html.erb
<div class="recipes-wrapper">
  <h1>Recipes#index</h1>
  <p>Find me in app/views/recipes/index.html.erb</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-wrapper">
  <div class="left-footer">
    <p>READY TO JOIN US</p>
    <p>Let's get to save food</p>
     <a href="#" class="contact-btn">CONTACT US</a>
  </div>
  <div class="right-footer">
    <div class="quick-social-wrapper">
      <div class="quick-links-wrapper">
        <p>Quick Links</p>
      </div>
       <div class="social-networks">
          <h3>Say Hello</h3>
          <div>
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-linkedin-in"></i></a>
          </div>
       </div>
    </div>
     <div class="copy-r">
       <p class="copy-right">Copyright © 2022 All Rights Reserved.</p>
       <p>Made it with <i class="fas fa-heart"></i> by <a href="https://www.linkedin.com/in/yamil-pedroso/">Foodamental</a></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wrapper">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-position">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/695/695934.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"   aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <!--<li class="nav-item active">
              <%#= link_to "Home", "#", class: "nav-link" %>
            </li>-->
            <li class="nav-item">
              <div class="current-user">
                <h5>Welcome</h5>
                <h4><%= @user.name %></h4>
              </div>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "yami.jpeg", class: "avatar dropdown-toggle avatar-border", id: "navbarDropdown", data: { bs_toggle: "dropdown" },   'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <div class="nav-menu">
      <ul class="nav-links">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", pages_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", "#", class: "nav-link" %>
        </li>
      </ul>
  </div>
  </div>
</div>

app/views/testimonials/_form.html.erb
<div class = "form">
  <%= simple_form_for(@testimonial) do |f| %>
    <%= f.input :name %>
    <%= f.input :profession %>
    <%= f.input :content %>
    <%= f.input :date %>
    <%= f.input :photo, as: :file%>

      <div class="form-actions">
        <%= f.button :submit, 'Save' %>
      </div>
  <% end %>
</div>

app/views/testimonials/destroy.html.erb
<h1>Testimonials#destroy</h1>
<p>Find me in app/views/testimonials/destroy.html.erb</p>

app/views/testimonials/edit.html.erb
<div class="edit-wrapper">
  <%= render "form", Testimonial: @testimonial %>
</div>

app/views/testimonials/index.html.erb
<div class="testimonials-wrapper">
  <div class="card-group">
     <% @testimonials.each do |testimonial| %>
      <% if testimonial.photo.attached? %>
      <div class="card-style">
        <%= link_to edit_testimonial_path(testimonial) do %>
          <%= cl_image_tag testimonial.photo.key, height: 300, width: 400, crop: :fill, class:"testimonial-img" %>
        <%end%>
        <div class="card-body">
          <h5 class="card-title"><%= testimonial.name %></h5>
          <p class="card-text"></p>
        </div>
        <div class="card-footer">
          <small class="text-muted"><%= testimonial.date %></small>
        </div>
      </div>
       <%end %>
    <% end %>
  </div>

  <% @testimonials.each.first(1).each do |testimonial| %>
      <div class="testimonial-text-wrapper">
        <h3 class="testimonial-title"><%= testimonial.name %></h3>
        <h2><%= testimonial.profession %></h2>
        <p><%= testimonial.content %></p>
      </div>
  <% end %>
</div>



<div class="btn-create-wrapper">
  <%= link_to "Create your testimonial", new_testimonial_path, class: "create-btn" %>
</div>

app/views/testimonials/new.html.erb
<div class="edit-wrapper">
  <%= render "form", Testimonial: @testimonial %>
</div>

app/views/testimonials/show.html.erb
<div class="show-wrapper">
  <%= cl_image_tag(@testimonial.photo.key, width: 600, height: 500, crop: :fill) %>
<div>

<div>
  <%= link_to "Edit this testimonial", edit_testimonial_path(@testimonial) %> |
  <%= link_to "Back to testimonials", testimonials_path %>

  <%= button_to "Destroy this testimonial", @testimonial, method: :delete, data: { confirm: 'Are you sure?'}%>
</div>

app/views/testimonials/update.html.erb
<h1>Testimonials#update</h1>
<p>Find me in app/views/testimonials/update.html.erb</p>